language: python
python:
    - 3.8
after_success:
    - bash <(curl -s https://codecov.io/bash)
install:
    - pip install -r requirements.txt
script:
    - python -m coverage run -m pytest
    - python -m coverage report -m scraping/*.py formatting/*.py
    - python -m pylint scraping/ formatting/
